services:
  harvest-wordpress-backend:
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: farai
      WORDPRESS_DB_PASSWORD: farai01294!
      WORDPRESS_DB_NAME: harvest_backend
    volumes:
      - wordpress_data:/var/www/html
      - ./harvest-wordpress-backend/wp-content:/var/www/html/wp-content
    depends_on:
      - db
    build:
      context: ./harvest-wordpress-backend
      dockerfile: Dockerfile

  db:
    image: mariadb:latest 
    environment:
      MYSQL_DATABASE: harvest_backend
      MYSQL_USER: farai
      MYSQL_PASSWORD: farai01294!
      MYSQL_ROOT_PASSWORD: farai01294!
    volumes:
      - db_data:/var/lib/mysql

  harvest-nodejs-api:
    build: ./harvest-nodejs-api
    ports:
      - "3000:3000"
    depends_on:
      - harvest-wordpress-backend
      - harvest-python-middleware

  harvest-python-middleware:
    build: ./harvest-python-middleware
    ports:
      - "5002:5002"

volumes:
  wordpress_data:
  db_data:
